linters:
  fast: false
  enable-all: true
  disable:
    - bodyclose
    - dupl
    - gochecknoglobals
    - gosec
    - lll
    - wsl
    - testpackage
    # deprecated linters
    - maligned
    - interfacer
    - ifshort
    - golint
    - scopelint
    - structcheck
    - deadcode
    - varcheck
    - nosnakecase
    - exhaustivestruct



linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: snake
  depguard:
    rules:
      main:
        allow:
          - "$gostd"
          - "github.com/selectel/domains-go/pkg/v2"
          - "github.com/jarcoal/httpmock"
          - "github.com/stretchr/testify/assert"
          - "github.com/stretchr/testify/require"
          - "github.com/stretchr/testify/suite"
        deny:
          - pkg: io/ioutil
            desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil